### ISSUE TITLE
CSTJ-2： NPE in auth commands

### ISSUE THREAD

**Issue by kylinsoong** [CustomizedTools/CustomizedTools-jar#2]
```
java.lang.NullPointerException
    at org.apache.cxf.jaxrs.client.AbstractClient.setupOutInterceptorChain(AbstractClient.java:879)
    at org.apache.cxf.jaxrs.client.AbstractClient.createMessage(AbstractClient.java:950)
    at org.apache.cxf.jaxrs.client.WebClient.finalizeMessage(WebClient.java:1118)
    at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1091)
    at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
    at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:865)
    at org.apache.cxf.jaxrs.client.WebClient.form(WebClient.java:401)
```

**Comment by kylinsoong** [comment]
From http://stackoverflow.com/questions/31156393/nullpointerexception-at-org-apache-cxf-jaxrs-client-abstractclient-setupoutinter
this should be a dependency isue
